//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3655
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3655.
// 
#pragma warning disable 1591

namespace VindiciaSelectIntegration.com.vindicia.soap {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'annotation' from namespace 'http://www.w3.org/2001/XMLSchema' was not handled.
    // CODEGEN: The optional WSDL extension element 'annotation' from namespace 'http://www.w3.org/2001/XMLSchema' was not handled.
    // CODEGEN: The optional WSDL extension element 'annotation' from namespace 'http://www.w3.org/2001/XMLSchema' was not handled.
    // CODEGEN: The optional WSDL extension element 'annotation' from namespace 'http://www.w3.org/2001/XMLSchema' was not handled.
    // CODEGEN: The optional WSDL extension element 'annotation' from namespace 'http://www.w3.org/2001/XMLSchema' was not handled.
    // CODEGEN: The optional WSDL extension element 'annotation' from namespace 'http://www.w3.org/2001/XMLSchema' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SelectBinding", Namespace="http://soap.vindicia.com/v1_1/Select")]
    public partial class Select : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback reportTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback billTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback refundTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchBillingResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchChargebacksOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchByMerchantTransactionIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Select() {
            this.Url = "https://soap.vindicia.com/soap.pl";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event reportTransactionsCompletedEventHandler reportTransactionsCompleted;
        
        /// <remarks/>
        public event billTransactionsCompletedEventHandler billTransactionsCompleted;
        
        /// <remarks/>
        public event refundTransactionsCompletedEventHandler refundTransactionsCompleted;
        
        /// <remarks/>
        public event fetchBillingResultsCompletedEventHandler fetchBillingResultsCompleted;
        
        /// <remarks/>
        public event fetchChargebacksCompletedEventHandler fetchChargebacksCompleted;
        
        /// <remarks/>
        public event fetchByMerchantTransactionIdCompletedEventHandler fetchByMerchantTransactionIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://soap.vindicia.com/v1_1/Select#reportTransactions", RequestNamespace="http://soap.vindicia.com/v1_1/Select", ResponseNamespace="http://soap.vindicia.com/v1_1/Select", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Return reportTransactions([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Authentication auth, [System.Xml.Serialization.XmlElementAttribute("transactions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Transaction[] transactions, [System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TransactionValidationResponse[] response) {
            object[] results = this.Invoke("reportTransactions", new object[] {
                        auth,
                        transactions});
            response = ((TransactionValidationResponse[])(results[1]));
            return ((Return)(results[0]));
        }
        
        /// <remarks/>
        public void reportTransactionsAsync(Authentication auth, Transaction[] transactions) {
            this.reportTransactionsAsync(auth, transactions, null);
        }
        
        /// <remarks/>
        public void reportTransactionsAsync(Authentication auth, Transaction[] transactions, object userState) {
            if ((this.reportTransactionsOperationCompleted == null)) {
                this.reportTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreportTransactionsOperationCompleted);
            }
            this.InvokeAsync("reportTransactions", new object[] {
                        auth,
                        transactions}, this.reportTransactionsOperationCompleted, userState);
        }
        
        private void OnreportTransactionsOperationCompleted(object arg) {
            if ((this.reportTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reportTransactionsCompleted(this, new reportTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://soap.vindicia.com/v1_1/Select#billTransactions", RequestNamespace="http://soap.vindicia.com/v1_1/Select", ResponseNamespace="http://soap.vindicia.com/v1_1/Select", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Return billTransactions([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Authentication auth, [System.Xml.Serialization.XmlElementAttribute("transactions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Transaction[] transactions, [System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TransactionValidationResponse[] response) {
            object[] results = this.Invoke("billTransactions", new object[] {
                        auth,
                        transactions});
            response = ((TransactionValidationResponse[])(results[1]));
            return ((Return)(results[0]));
        }
        
        /// <remarks/>
        public void billTransactionsAsync(Authentication auth, Transaction[] transactions) {
            this.billTransactionsAsync(auth, transactions, null);
        }
        
        /// <remarks/>
        public void billTransactionsAsync(Authentication auth, Transaction[] transactions, object userState) {
            if ((this.billTransactionsOperationCompleted == null)) {
                this.billTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbillTransactionsOperationCompleted);
            }
            this.InvokeAsync("billTransactions", new object[] {
                        auth,
                        transactions}, this.billTransactionsOperationCompleted, userState);
        }
        
        private void OnbillTransactionsOperationCompleted(object arg) {
            if ((this.billTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.billTransactionsCompleted(this, new billTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://soap.vindicia.com/v1_1/Select#refundTransactions", RequestNamespace="http://soap.vindicia.com/v1_1/Select", ResponseNamespace="http://soap.vindicia.com/v1_1/Select", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Return refundTransactions([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Authentication auth, [System.Xml.Serialization.XmlElementAttribute("refunds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] refunds, [System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TransactionValidationResponse[] response) {
            object[] results = this.Invoke("refundTransactions", new object[] {
                        auth,
                        refunds});
            response = ((TransactionValidationResponse[])(results[1]));
            return ((Return)(results[0]));
        }
        
        /// <remarks/>
        public void refundTransactionsAsync(Authentication auth, string[] refunds) {
            this.refundTransactionsAsync(auth, refunds, null);
        }
        
        /// <remarks/>
        public void refundTransactionsAsync(Authentication auth, string[] refunds, object userState) {
            if ((this.refundTransactionsOperationCompleted == null)) {
                this.refundTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrefundTransactionsOperationCompleted);
            }
            this.InvokeAsync("refundTransactions", new object[] {
                        auth,
                        refunds}, this.refundTransactionsOperationCompleted, userState);
        }
        
        private void OnrefundTransactionsOperationCompleted(object arg) {
            if ((this.refundTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.refundTransactionsCompleted(this, new refundTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://soap.vindicia.com/v1_1/Select#fetchBillingResults", RequestNamespace="http://soap.vindicia.com/v1_1/Select", ResponseNamespace="http://soap.vindicia.com/v1_1/Select", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Return fetchBillingResults([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Authentication auth, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime timestamp, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime endTimestamp, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int page, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pageSize, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSizeSpecified, [System.Xml.Serialization.XmlElementAttribute("transactions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out Transaction[] transactions) {
            object[] results = this.Invoke("fetchBillingResults", new object[] {
                        auth,
                        timestamp,
                        endTimestamp,
                        page,
                        pageSpecified,
                        pageSize,
                        pageSizeSpecified});
            transactions = ((Transaction[])(results[1]));
            return ((Return)(results[0]));
        }
        
        /// <remarks/>
        public void fetchBillingResultsAsync(Authentication auth, System.DateTime timestamp, System.DateTime endTimestamp, int page, bool pageSpecified, int pageSize, bool pageSizeSpecified) {
            this.fetchBillingResultsAsync(auth, timestamp, endTimestamp, page, pageSpecified, pageSize, pageSizeSpecified, null);
        }
        
        /// <remarks/>
        public void fetchBillingResultsAsync(Authentication auth, System.DateTime timestamp, System.DateTime endTimestamp, int page, bool pageSpecified, int pageSize, bool pageSizeSpecified, object userState) {
            if ((this.fetchBillingResultsOperationCompleted == null)) {
                this.fetchBillingResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchBillingResultsOperationCompleted);
            }
            this.InvokeAsync("fetchBillingResults", new object[] {
                        auth,
                        timestamp,
                        endTimestamp,
                        page,
                        pageSpecified,
                        pageSize,
                        pageSizeSpecified}, this.fetchBillingResultsOperationCompleted, userState);
        }
        
        private void OnfetchBillingResultsOperationCompleted(object arg) {
            if ((this.fetchBillingResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchBillingResultsCompleted(this, new fetchBillingResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://soap.vindicia.com/v1_1/Select#fetchChargebacks", RequestNamespace="http://soap.vindicia.com/v1_1/Select", ResponseNamespace="http://soap.vindicia.com/v1_1/Select", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Return fetchChargebacks([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Authentication auth, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime timestamp, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime endTimestamp, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int page, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pageSize, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSizeSpecified, [System.Xml.Serialization.XmlElementAttribute("chargebacks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out Chargeback[] chargebacks) {
            object[] results = this.Invoke("fetchChargebacks", new object[] {
                        auth,
                        timestamp,
                        endTimestamp,
                        page,
                        pageSpecified,
                        pageSize,
                        pageSizeSpecified});
            chargebacks = ((Chargeback[])(results[1]));
            return ((Return)(results[0]));
        }
        
        /// <remarks/>
        public void fetchChargebacksAsync(Authentication auth, System.DateTime timestamp, System.DateTime endTimestamp, int page, bool pageSpecified, int pageSize, bool pageSizeSpecified) {
            this.fetchChargebacksAsync(auth, timestamp, endTimestamp, page, pageSpecified, pageSize, pageSizeSpecified, null);
        }
        
        /// <remarks/>
        public void fetchChargebacksAsync(Authentication auth, System.DateTime timestamp, System.DateTime endTimestamp, int page, bool pageSpecified, int pageSize, bool pageSizeSpecified, object userState) {
            if ((this.fetchChargebacksOperationCompleted == null)) {
                this.fetchChargebacksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchChargebacksOperationCompleted);
            }
            this.InvokeAsync("fetchChargebacks", new object[] {
                        auth,
                        timestamp,
                        endTimestamp,
                        page,
                        pageSpecified,
                        pageSize,
                        pageSizeSpecified}, this.fetchChargebacksOperationCompleted, userState);
        }
        
        private void OnfetchChargebacksOperationCompleted(object arg) {
            if ((this.fetchChargebacksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchChargebacksCompleted(this, new fetchChargebacksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://soap.vindicia.com/v1_1/Select#fetchByMerchantTransactionId", RequestNamespace="http://soap.vindicia.com/v1_1/Select", ResponseNamespace="http://soap.vindicia.com/v1_1/Select", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Return fetchByMerchantTransactionId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Authentication auth, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchantTransactionId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out Transaction transaction) {
            object[] results = this.Invoke("fetchByMerchantTransactionId", new object[] {
                        auth,
                        merchantTransactionId});
            transaction = ((Transaction)(results[1]));
            return ((Return)(results[0]));
        }
        
        /// <remarks/>
        public void fetchByMerchantTransactionIdAsync(Authentication auth, string merchantTransactionId) {
            this.fetchByMerchantTransactionIdAsync(auth, merchantTransactionId, null);
        }
        
        /// <remarks/>
        public void fetchByMerchantTransactionIdAsync(Authentication auth, string merchantTransactionId, object userState) {
            if ((this.fetchByMerchantTransactionIdOperationCompleted == null)) {
                this.fetchByMerchantTransactionIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchByMerchantTransactionIdOperationCompleted);
            }
            this.InvokeAsync("fetchByMerchantTransactionId", new object[] {
                        auth,
                        merchantTransactionId}, this.fetchByMerchantTransactionIdOperationCompleted, userState);
        }
        
        private void OnfetchByMerchantTransactionIdOperationCompleted(object arg) {
            if ((this.fetchByMerchantTransactionIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchByMerchantTransactionIdCompleted(this, new fetchByMerchantTransactionIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public partial class Authentication {
        
        private string versionField;
        
        private string loginField;
        
        private string passwordField;
        
        private string evidField;
        
        private string userAgentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string evid {
            get {
                return this.evidField;
            }
            set {
                this.evidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public partial class Chargeback {
        
        private string vIDField;
        
        private decimal amountField;
        
        private string currencyField;
        
        private decimal presentmentAmountField;
        
        private bool presentmentAmountFieldSpecified;
        
        private string presentmentCurrencyField;
        
        private string divisionNumberField;
        
        private string reasonCodeField;
        
        private string caseNumberField;
        
        private string referenceNumberField;
        
        private string merchantNumberField;
        
        private string merchantTransactionIdField;
        
        private System.DateTime merchantTransactionTimestampField;
        
        private bool merchantTransactionTimestampFieldSpecified;
        
        private System.DateTime processorReceivedTimestampField;
        
        private System.DateTime postedTimestampField;
        
        private System.DateTime statusChangedTimestampField;
        
        private bool statusChangedTimestampFieldSpecified;
        
        private ChargebackStatus statusField;
        
        private string merchantUserIdField;
        
        private string noteField;
        
        private NameValuePair[] nameValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VID {
            get {
                return this.vIDField;
            }
            set {
                this.vIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal presentmentAmount {
            get {
                return this.presentmentAmountField;
            }
            set {
                this.presentmentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presentmentAmountSpecified {
            get {
                return this.presentmentAmountFieldSpecified;
            }
            set {
                this.presentmentAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string presentmentCurrency {
            get {
                return this.presentmentCurrencyField;
            }
            set {
                this.presentmentCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string divisionNumber {
            get {
                return this.divisionNumberField;
            }
            set {
                this.divisionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string caseNumber {
            get {
                return this.caseNumberField;
            }
            set {
                this.caseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string merchantNumber {
            get {
                return this.merchantNumberField;
            }
            set {
                this.merchantNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string merchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime merchantTransactionTimestamp {
            get {
                return this.merchantTransactionTimestampField;
            }
            set {
                this.merchantTransactionTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool merchantTransactionTimestampSpecified {
            get {
                return this.merchantTransactionTimestampFieldSpecified;
            }
            set {
                this.merchantTransactionTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime processorReceivedTimestamp {
            get {
                return this.processorReceivedTimestampField;
            }
            set {
                this.processorReceivedTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime postedTimestamp {
            get {
                return this.postedTimestampField;
            }
            set {
                this.postedTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime statusChangedTimestamp {
            get {
                return this.statusChangedTimestampField;
            }
            set {
                this.statusChangedTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusChangedTimestampSpecified {
            get {
                return this.statusChangedTimestampFieldSpecified;
            }
            set {
                this.statusChangedTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ChargebackStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string merchantUserId {
            get {
                return this.merchantUserIdField;
            }
            set {
                this.merchantUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nameValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NameValuePair[] nameValues {
            get {
                return this.nameValuesField;
            }
            set {
                this.nameValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public enum ChargebackStatus {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Retrieval,
        
        /// <remarks/>
        Responded,
        
        /// <remarks/>
        Legitimate,
        
        /// <remarks/>
        Challenged,
        
        /// <remarks/>
        Represented,
        
        /// <remarks/>
        Won,
        
        /// <remarks/>
        Lost,
        
        /// <remarks/>
        CollectionsNew,
        
        /// <remarks/>
        CollectionsWon,
        
        /// <remarks/>
        CollectionsLost,
        
        /// <remarks/>
        Expired,
        
        /// <remarks/>
        Pass,
        
        /// <remarks/>
        Incomplete,
        
        /// <remarks/>
        NewSecondChargeback,
        
        /// <remarks/>
        Duplicate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public partial class NameValuePair {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public partial class TransactionValidationResponse {
        
        private string merchantTransactionIdField;
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string merchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public partial class Return {
        
        private int returnCodeField;
        
        private string returnStringField;
        
        private string soapIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string returnString {
            get {
                return this.returnStringField;
            }
            set {
                this.returnStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string soapId {
            get {
                return this.soapIdField;
            }
            set {
                this.soapIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public partial class Transaction {
        
        private string vIDField;
        
        private System.DateTime timestampField;
        
        private decimal amountField;
        
        private string currencyField;
        
        private TransactionStatusType statusField;
        
        private string divisionNumberField;
        
        private string merchantTransactionIdField;
        
        private string selectTransactionIdField;
        
        private string selectRefundIdField;
        
        private string subscriptionIdField;
        
        private System.DateTime subscriptionStartDateField;
        
        private bool subscriptionStartDateFieldSpecified;
        
        private BillingIntervalType billingFrequencyField;
        
        private bool billingFrequencyFieldSpecified;
        
        private System.DateTime previousBillingDateField;
        
        private bool previousBillingDateFieldSpecified;
        
        private int previousBillingCountField;
        
        private bool previousBillingCountFieldSpecified;
        
        private string customerIdField;
        
        private string paymentMethodIdField;
        
        private bool paymentMethodIsTokenizedField;
        
        private string creditCardAccountField;
        
        private string creditCardAccountHashField;
        
        private string creditCardExpirationDateField;
        
        private string accountHolderNameField;
        
        private string billingAddressLine1Field;
        
        private string billingAddressLine2Field;
        
        private string billingAddressLine3Field;
        
        private string billingAddressCityField;
        
        private string billingAddressCountyField;
        
        private string billingAddressDistrictField;
        
        private string billingAddressPostalCodeField;
        
        private string billingAddressCountryField;
        
        private NameValuePair[] nameValuesField;
        
        private string affiliateIdField;
        
        private string affiliateSubIdField;
        
        private string billingStatementIdentifierField;
        
        private string authCodeField;
        
        private string avsCodeField;
        
        private string cvnCodeField;
        
        private bool creditCardAccountUpdatedField;
        
        private bool creditCardAccountUpdatedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VID {
            get {
                return this.vIDField;
            }
            set {
                this.vIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransactionStatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string divisionNumber {
            get {
                return this.divisionNumberField;
            }
            set {
                this.divisionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string merchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string selectTransactionId {
            get {
                return this.selectTransactionIdField;
            }
            set {
                this.selectTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string selectRefundId {
            get {
                return this.selectRefundIdField;
            }
            set {
                this.selectRefundIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subscriptionId {
            get {
                return this.subscriptionIdField;
            }
            set {
                this.subscriptionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime subscriptionStartDate {
            get {
                return this.subscriptionStartDateField;
            }
            set {
                this.subscriptionStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subscriptionStartDateSpecified {
            get {
                return this.subscriptionStartDateFieldSpecified;
            }
            set {
                this.subscriptionStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BillingIntervalType billingFrequency {
            get {
                return this.billingFrequencyField;
            }
            set {
                this.billingFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool billingFrequencySpecified {
            get {
                return this.billingFrequencyFieldSpecified;
            }
            set {
                this.billingFrequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime previousBillingDate {
            get {
                return this.previousBillingDateField;
            }
            set {
                this.previousBillingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool previousBillingDateSpecified {
            get {
                return this.previousBillingDateFieldSpecified;
            }
            set {
                this.previousBillingDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int previousBillingCount {
            get {
                return this.previousBillingCountField;
            }
            set {
                this.previousBillingCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool previousBillingCountSpecified {
            get {
                return this.previousBillingCountFieldSpecified;
            }
            set {
                this.previousBillingCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paymentMethodId {
            get {
                return this.paymentMethodIdField;
            }
            set {
                this.paymentMethodIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool paymentMethodIsTokenized {
            get {
                return this.paymentMethodIsTokenizedField;
            }
            set {
                this.paymentMethodIsTokenizedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creditCardAccount {
            get {
                return this.creditCardAccountField;
            }
            set {
                this.creditCardAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creditCardAccountHash {
            get {
                return this.creditCardAccountHashField;
            }
            set {
                this.creditCardAccountHashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creditCardExpirationDate {
            get {
                return this.creditCardExpirationDateField;
            }
            set {
                this.creditCardExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountHolderName {
            get {
                return this.accountHolderNameField;
            }
            set {
                this.accountHolderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingAddressLine1 {
            get {
                return this.billingAddressLine1Field;
            }
            set {
                this.billingAddressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingAddressLine2 {
            get {
                return this.billingAddressLine2Field;
            }
            set {
                this.billingAddressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingAddressLine3 {
            get {
                return this.billingAddressLine3Field;
            }
            set {
                this.billingAddressLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingAddressCity {
            get {
                return this.billingAddressCityField;
            }
            set {
                this.billingAddressCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingAddressCounty {
            get {
                return this.billingAddressCountyField;
            }
            set {
                this.billingAddressCountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingAddressDistrict {
            get {
                return this.billingAddressDistrictField;
            }
            set {
                this.billingAddressDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingAddressPostalCode {
            get {
                return this.billingAddressPostalCodeField;
            }
            set {
                this.billingAddressPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingAddressCountry {
            get {
                return this.billingAddressCountryField;
            }
            set {
                this.billingAddressCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nameValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NameValuePair[] nameValues {
            get {
                return this.nameValuesField;
            }
            set {
                this.nameValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string affiliateId {
            get {
                return this.affiliateIdField;
            }
            set {
                this.affiliateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string affiliateSubId {
            get {
                return this.affiliateSubIdField;
            }
            set {
                this.affiliateSubIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingStatementIdentifier {
            get {
                return this.billingStatementIdentifierField;
            }
            set {
                this.billingStatementIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avsCode {
            get {
                return this.avsCodeField;
            }
            set {
                this.avsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cvnCode {
            get {
                return this.cvnCodeField;
            }
            set {
                this.cvnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool creditCardAccountUpdated {
            get {
                return this.creditCardAccountUpdatedField;
            }
            set {
                this.creditCardAccountUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creditCardAccountUpdatedSpecified {
            get {
                return this.creditCardAccountUpdatedFieldSpecified;
            }
            set {
                this.creditCardAccountUpdatedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public enum TransactionStatusType {
        
        /// <remarks/>
        Authorized,
        
        /// <remarks/>
        Captured,
        
        /// <remarks/>
        Settled,
        
        /// <remarks/>
        Refunded,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        BillingNotAttempted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.vindicia.com/v1_1/SelectTypes")]
    public enum BillingIntervalType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Non-recurring")]
        Nonrecurring,
        
        /// <remarks/>
        Daily,
        
        /// <remarks/>
        Weekly,
        
        /// <remarks/>
        Monthly,
        
        /// <remarks/>
        Quarterly,
        
        /// <remarks/>
        Yearly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void reportTransactionsCompletedEventHandler(object sender, reportTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reportTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reportTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Return)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TransactionValidationResponse[] response {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionValidationResponse[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void billTransactionsCompletedEventHandler(object sender, billTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class billTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal billTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Return)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TransactionValidationResponse[] response {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionValidationResponse[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void refundTransactionsCompletedEventHandler(object sender, refundTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class refundTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal refundTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Return)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TransactionValidationResponse[] response {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionValidationResponse[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void fetchBillingResultsCompletedEventHandler(object sender, fetchBillingResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchBillingResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchBillingResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Return)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Transaction[] transactions {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaction[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void fetchChargebacksCompletedEventHandler(object sender, fetchChargebacksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchChargebacksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchChargebacksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Return)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Chargeback[] chargebacks {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Chargeback[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void fetchByMerchantTransactionIdCompletedEventHandler(object sender, fetchByMerchantTransactionIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchByMerchantTransactionIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchByMerchantTransactionIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Return)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Transaction transaction {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaction)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591

