import com.vindicia.client.*;

public class CreateAccount {
	
	public static void main(String[ ] args) {
		System.out.println("*****ACCOUNT CREATE Example *******");
		
		
		com.vindicia.client.ClientConstants.SOAP_LOGIN = "XXXXXXX";
		com.vindicia.client.ClientConstants.SOAP_PASSWORD = "XXXXXXX";
		
		
		
		com.vindicia.client.ClientConstants.DEFAULT_VINDICIA_SERVICE_URL= "https://soap.prodtest.sj.vindicia.com";
		com.vindicia.client.ClientConstants.DEFAULT_TIMEOUT = 20000;
		
		String uniqueId = "" + System.currentTimeMillis();
		
		//Start:create Account
		com.vindicia.client.Account acct = new com.vindicia.client.Account();
		
		//no need to set VID, it is automatically generated by CB when update method is called
		boolean warnValue = false;
		acct.setMerchantAccountId("AccountID"+uniqueId); 
		acct.setEmailAddress("MyEmail@gmail.com");
		acct.setName("Acct Name "+uniqueId);
		acct.setWarnBeforeAutobilling(warnValue);
		acct.setEmailTypePreference(com.vindicia.soap.v22_0.Vindicia.EmailPreference.plaintext);
		
		
		com.vindicia.client.Address addr = new com.vindicia.client.Address();
		addr.setName("My Name");
		addr.setAddr1("2226 Mary Ave");
		addr.setCity("Santa Clara");
		addr.setPostalCode("95050");
		addr.setCountry("US");
		addr.setPhone("408408408");
		
		acct.setShippingAddress(addr);
		
		
		//End:create Account
		
		
		try {
			
			//Create or Update
			boolean created = acct.update(null); 
			// if we are here, we got a 200-OK response from the server
			if (created) {
				System.out.print("Successfully created account " + acct.getMerchantAccountId());
				System.out.println(", Vindicia assigned  ID " + acct.getVID());
			}
			else {
				// This product already existed in CashBox and was only updated by this call
				System.out.print("Successfully updated account " + acct.getMerchantAccountId());
			
			}
			
		}
			
			
		catch (VindiciaReturnException vre) {
			// VindiciaReturnException indicates a non-200 response code from the server
			
			System.out.println("Account creation/update failed, return code: " + vre.getReturnCode() + " return string: '" + vre.getMessage() + "'" + " Soap id: " + vre.getSoapId());
			
		}
		catch (Exception e) {
			// Handle more serious exception such as timeout or network drop here
			System.out.println("Account creation/update failed" );
			e.printStackTrace();
			
		}
		
	}
	

}
